tasks:
  - name: global
    init: virtualenv env
          . env/bin/activate
          pip install -r requirements.txt
          pip install django_cleanup channels reportlab stripe gopay

    command: django-admin --version
             gp sync-done global

  - name: postgressDb
    init: gp sync-await global
          docker-compose up
          gp sync-done postgressDb

  - name: migrattion
    command: gp sync-await postgressDb
             python manage.py makemigrations
             python manage.py migrate
             python manage.py createsuperuser
             python manage.py migrate




