tasks:
  - name: global
    init: |
      virtualenv env
      .env/bin/activate
      pip install -r requirements.txt
      pip install django_cleanup channels reportlab stripe gopay
    
    command: |
        django-admin --version
        python manage.py show_urls 
        gp sync-done global-gp

  - name: postgressDb
    init: | 
          gp sync-await global-gp
          docker-compose up
          gp sync-done postgressDb-gp

  - name: migrattion
    command: |
             gp sync-await postgressDb-gp
             python manage.py makemigrations
             python manage.py migrate
             python manage.py createsuperuser
             python manage.py runserver

vscode:
  extensions:
    - batisteo.vscode-django
    - ms-azuretools.vscode-docker
